# config/api_config.yaml

# Optional: Default MLflow Model URI if not set by environment variable
# default_model_uri: "runs:/YOUR_RUN_ID/model"

# Feature Engineering parameters needed by the API
# This should ideally match the parameters used during training
# Alternatively, log these parameters with the model in MLflow
feature_engineering:
  lags: [1, 2, 3, 5, 10]

# Training configuration snippet (needed for feature consistency check)
# Again, ideally load this from MLflow artifact if possible
training:
  feature_columns:
    - 'SMA_10'
    - 'RSI_14'
    - 'Close_lag_1'
    - 'Close_lag_2'
    - 'Close_lag_3'
    - 'Close_lag_5'
    - 'Close_lag_10' 