# config/training_config.yaml
feature_engineering:
  lags: [1, 2, 3, 5, 10] # Example lag features
  target_horizon: 1      # Predict 1 day ahead

training:
  feature_columns:        # List the features used for training
    - 'SMA_10'
    - 'RSI_14'
    - 'Close_lag_1'
    - 'Close_lag_2'
    - 'Close_lag_3'
    - 'Close_lag_5'
    - 'Close_lag_10'
    # Add other engineered features here
  target_column: 'target_binary' # Example: Predict binary direction
  test_split_ratio: 0.2

model:
  type: 'RandomForestClassifier' # Or LogisticRegression, etc.
  params: # Hyperparameters for the model
    n_estimators: 100
    max_depth: 10
    min_samples_split: 5
    random_state: 42
    # Add other model-specific parameters 